[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
absolute_monarchy = "ADp9DgS9ZpsVDCXb4ysDjJoB1d8cL3CUmm4ErwVtqWzu"
conviction = "ATsZoBzoVyPF97HLn9kt2ffNSGcnYwUApbNxfsVknNVr"
military_junta = "2fPj7RDkm4FJouSo6DE6vHbE5rjTvdZPnnxJUgFvYVm2"
standard = "7aQvq1fEiDXqK36H7mW8MSTGdnHn6XAHDd9pauZwZXGQ"
the_ark_program = "48qaGS4sA7bqiXYE6SyzaFiAb7QNit1A7vdib7LXhW2V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
